### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by shayanxtreme** [anmol65233/-chatgpt-wordpress-api#1]
Parse error: syntax error, unexpected '}', expecting ';' or ',' in /home/clariodg/shayangamez.com/wp-content/plugins/chatgpt-wordpress-api/chatgpt.php on line

**Comment by anmol65233** [comment]
fixed

**Comment by anmol65233** [comment]
Fixed 

> Parse error: syntax error, unexpected '}', expecting ';' or ',' in /home/clariodg/shayangamez.com/wp-content/plugins/chatgpt-wordpress-api/chatgpt.php on line

**Comment by shayanxtreme** [comment]
but how to use ?

**Comment by anmol65233** [comment]
Step1: Install the plugin (Zip file)
Step2: Add your secret key (SK) into the backend form and save.
Step3: There will be shortcode in the form display. Add that code to the frontend where you want to show the frontend form

**Comment by anmol65233** [comment]
Issue fixed
